declare const styles: {
    HireDate: string;
    backgroundImgBallons: string;
    documentCard: string;
    documentCardWrapper: string;
    container: string;
    today: string;
    centered: string;
    persona: string;
    actions: string;
    row: string;
    column: string;
    'ms-Grid': string;
    title: string;
    centeredHeader: string;
    subTitle: string;
    description: string;
    button: string;
    label: string;
};
export default styles;
