declare const styles: {
    menuButton: string;
    topPanel: string;
    menuWrap: string;
    categoryItem: string;
    menuItem: string;
    grid: string;
    row: string;
    col1sm: string;
    col2sm: string;
    col3sm: string;
    col4sm: string;
    col5sm: string;
    col6sm: string;
    col7sm: string;
    col8sm: string;
    col9sm: string;
    col10sm: string;
    col11sm: string;
    col12sm: string;
    col1: string;
    col2: string;
    col3: string;
    col4: string;
    col5: string;
    col6: string;
    col7: string;
    col8: string;
    col9: string;
    col10: string;
    col11: string;
    col12: string;
    hiddensm: string;
};
export default styles;
